In [2]:
import tensorflow as tf

In [45]:
params = tf.constant([
    (0, 0, 1, 0, 2),
    [3, 0, 0, 0, 4],
    [0, 5, 0, 6, 0]])
indices = tf.constant(
    [0,2])
tf.gather(params, indices)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 0, 1, 0, 2],
       [0, 5, 0, 6, 0]])>

In [27]:
params = tf.constant([
    (0, 0, 1, 0, 2),
    [3, 0, 0, 0, 4],
    [0, 5, 0, 6, 0]])
indices = tf.constant(
    [2, 4, 3])

In [28]:
tf.gather(params, indices, axis=1).numpy()

array([[1, 2, 0],
       [0, 4, 0],
       [0, 0, 6]])

In [43]:
tf.gather(params, tf.constant([2, 4, 3]), axis=1, batch_dims=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 6])>

In [17]:
params = tf.constant([
    [0, 0, 1, 0, 2],
    [3, 0, 0, 0, 4],
    [0, 5, 0, 6, 0]])
indices = tf.constant([
    [2, 4],
    [0, 4],
    [1, 3]])
tf.gather(params, indices, axis=1, batch_dims=1).numpy()

array([[1, 2],
       [3, 4],
       [5, 6]])

In [2]:
indices = tf.constant([[1],
             [2]])
params = tf.constant([[[-1.0228521 ,  0.7286925 , -0.84171396],
                       [-0.917749  ,  0.23967385,  0.24835128],
                       [-0.12899126,  0.48454696, -0.8943562 ]],
                      [[-0.17912224,  0.3945618 , -0.5160401 ],
                       [-0.29391372,  0.0176767 ,  1.055536  ],
                       [ 0.3983369 , -0.576468  ,  0.77371967]]])
tf.gather(params, indices, batch_dims=1)

<tf.Tensor: shape=(2, 1, 3), dtype=float32, numpy=
array([[[-0.917749  ,  0.23967385,  0.24835128]],

       [[ 0.3983369 , -0.576468  ,  0.77371967]]], dtype=float32)>

In [27]:
indices = tf.constant([1, 2])
params = tf.constant([[[-1.0228521 ,  0.7286925 , -0.84171396],
                       [-0.917749  ,  0.23967385,  0.24835128],
                       [-0.12899126,  0.48454696, -0.8943562 ]],
                      [[-0.17912224,  0.3945618 , -0.5160401 ],
                       [-0.29391372,  0.0176767 ,  1.055536  ],
                       [ 0.3983369 , -0.576468  ,  0.77371967]]])
tf.gather(params, indices, axis=1, batch_dims=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.917749  ,  0.23967385,  0.24835128],
       [ 0.3983369 , -0.576468  ,  0.77371967]], dtype=float32)>

In [23]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
tf.gather(params, indices=[[2],[1],[2],[2]], axis=1, batch_dims=1)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 2.],
       [11.],
       [22.],
       [32.]], dtype=float32)>

In [15]:

current=[
        [0,7,1,2,2],
        [1,7,3,4,3],
        [2,7,5,6,6],
        [3,7,7,8,7],
        [4,7,7,8,7],
        [5,7,7,8,7]
        ]

current =tf.constant(current)
print(current)
points_e = tf.expand_dims(current, axis=2)
points_e

tf.Tensor(
[[0 7 1 2 2]
 [1 7 3 4 3]
 [2 7 5 6 6]
 [3 7 7 8 7]
 [4 7 7 8 7]
 [5 7 7 8 7]], shape=(6, 5), dtype=int32)


<tf.Tensor: shape=(6, 5, 1), dtype=int32, numpy=
array([[[0],
        [7],
        [1],
        [2],
        [2]],

       [[1],
        [7],
        [3],
        [4],
        [3]],

       [[2],
        [7],
        [5],
        [6],
        [6]],

       [[3],
        [7],
        [7],
        [8],
        [7]],

       [[4],
        [7],
        [7],
        [8],
        [7]],

       [[5],
        [7],
        [7],
        [8],
        [7]]])>