In [3]:
! pip install tensorflow

Looking in indexes: https://pypi.douban.com/simple


In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)
print(tf.test.is_gpu_available())
print(tf.config.list_physical_devices('GPU'))

2.9.1
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
True
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [3]:
params = tf.constant([
    (0, 0, 1, 0, 2),
    [3, 0, 0, 0, 4],
    [0, 5, 0, 6, 0]])
indices = tf.constant(
    [0,2])
tf.gather(params, indices)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 0, 1, 0, 2],
       [0, 5, 0, 6, 0]])>

In [3]:
params = tf.constant([
    (0, 0, 1, 0, 2),
    [3, 0, 0, 0, 4],
    [0, 5, 0, 6, 0]])
indices = tf.constant(
    [2, 4, 3])

In [4]:
tf.gather(params, indices, axis=1).numpy()

array([[1, 2, 0],
       [0, 4, 0],
       [0, 0, 6]], dtype=int32)

In [5]:
tf.gather(params, tf.constant([2, 4, 3]), axis=1, batch_dims=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 6], dtype=int32)>

In [6]:
params = tf.constant([
    [0, 0, 1, 0, 2],
    [3, 0, 0, 0, 4],
    [0, 5, 0, 6, 0]])
indices = tf.constant([
    [2, 4],
    [0, 4],
    [1, 3]])
tf.gather(params, indices, axis=1, batch_dims=1).numpy()

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [7]:
indices = tf.constant([[1],
             [2]])
params = tf.constant([[[-1.0228521 ,  0.7286925 , -0.84171396],
                       [-0.917749  ,  0.23967385,  0.24835128],
                       [-0.12899126,  0.48454696, -0.8943562 ]],
                      [[-0.17912224,  0.3945618 , -0.5160401 ],
                       [-0.29391372,  0.0176767 ,  1.055536  ],
                       [ 0.3983369 , -0.576468  ,  0.77371967]]])
tf.gather(params, indices, batch_dims=1)

<tf.Tensor: shape=(2, 1, 3), dtype=float32, numpy=
array([[[-0.917749  ,  0.23967385,  0.24835128]],

       [[ 0.3983369 , -0.576468  ,  0.77371967]]], dtype=float32)>

In [27]:
indices = tf.constant([1, 2])
params = tf.constant([[[-1.0228521 ,  0.7286925 , -0.84171396],
                       [-0.917749  ,  0.23967385,  0.24835128],
                       [-0.12899126,  0.48454696, -0.8943562 ]],
                      [[-0.17912224,  0.3945618 , -0.5160401 ],
                       [-0.29391372,  0.0176767 ,  1.055536  ],
                       [ 0.3983369 , -0.576468  ,  0.77371967]]])
tf.gather(params, indices, axis=1, batch_dims=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.917749  ,  0.23967385,  0.24835128],
       [ 0.3983369 , -0.576468  ,  0.77371967]], dtype=float32)>

In [23]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
tf.gather(params, indices=[[2],[1],[2],[2]], axis=1, batch_dims=1)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 2.],
       [11.],
       [22.],
       [32.]], dtype=float32)>

In [15]:

current=[
        [0,7,1,2,2],
        [1,7,3,4,3],
        [2,7,5,6,6],
        [3,7,7,8,7],
        [4,7,7,8,7],
        [5,7,7,8,7]
        ]

current =tf.constant(current)
print(current)
points_e = tf.expand_dims(current, axis=2)
points_e

tf.Tensor(
[[0 7 1 2 2]
 [1 7 3 4 3]
 [2 7 5 6 6]
 [3 7 7 8 7]
 [4 7 7 8 7]
 [5 7 7 8 7]], shape=(6, 5), dtype=int32)


<tf.Tensor: shape=(6, 5, 1), dtype=int32, numpy=
array([[[0],
        [7],
        [1],
        [2],
        [2]],

       [[1],
        [7],
        [3],
        [4],
        [3]],

       [[2],
        [7],
        [5],
        [6],
        [6]],

       [[3],
        [7],
        [7],
        [8],
        [7]],

       [[4],
        [7],
        [7],
        [8],
        [7]],

       [[5],
        [7],
        [7],
        [8],
        [7]]])>

In [3]:
x = tf.constant([1.8, 2.2], dtype=tf.float32)
tf.cast(x, tf.int32) 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [6]:
import re
re_han = re.compile("([\u4E00-\u9Fa5a-zA-Z0-9+#&]+)", re.U)
text = 'compile 函数用于编译正则表达式，生成一个正则表达式（ Pattern ）对象，供 match() 和 search这两个函数使.'
re_han.split(text)

['',
 'compile',
 ' ',
 '函数用于编译正则表达式',
 '，',
 '生成一个正则表达式',
 '（ ',
 'Pattern',
 ' ）',
 '对象',
 '，',
 '供',
 ' ',
 'match',
 '() ',
 '和',
 ' ',
 'search这两个函数使',
 '.']