In [1]:
import tensorflow as tf
from tensorflow.keras import backend as K
print(tf.__version__)

2.5.0


In [2]:
labels = tf.constant([[0, 1, 1], [0, 0, 1], [0, 1, 1]], dtype='float32')
logits = tf.constant([[-18.6, 0.51, 0.51], [2.94, -12.8, 0.11], [1.28, -11.8, 0.21]], dtype='float32')

y_pred = tf.math.sigmoid(logits)

## 每个样本的损失

In [3]:
bce = tf.keras.losses.BinaryCrossentropy(from_logits=True, reduction=tf.keras.losses.Reduction.NONE)
bce(labels, logits)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.31354222, 1.2103926 , 4.6396613 ], dtype=float32)>

In [ ]:
bce = tf.keras.losses.BinaryCrossentropy(reduction=tf.keras.losses.Reduction.NONE)
bce(labels, y_pred)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.23515657, 1.4957578 ], dtype=float32)>

In [ ]:
loss = tf.keras.losses.binary_crossentropy(labels, logits, from_logits=True)
loss

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.23515666, 1.4957594 ], dtype=float32)>

In [ ]:
tf.nn.sigmoid_cross_entropy_with_logits(labels, logits)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8.3583869e-09, 4.7031331e-01],
       [2.9915159e+00, 2.7607682e-06]], dtype=float32)>

In [ ]:
tf.keras.backend.mean(tf.keras.backend.binary_crossentropy(labels, logits, from_logits=True),axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.23515666, 1.4957594 ], dtype=float32)>

## 返回平均损失

In [ ]:
bce = tf.keras.losses.BinaryCrossentropy(from_logits=True)
bce(labels, logits).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=float32, numpy=0.865458>>

In [ ]:
loss = tf.keras.losses.binary_crossentropy(labels, logits, from_logits=True)
tf.math.reduce_mean(loss)

<tf.Tensor: shape=(), dtype=float32, numpy=0.865458>

In [ ]:
tf.keras.backend.mean(tf.keras.backend.binary_crossentropy(labels, logits, from_logits=True))

<tf.Tensor: shape=(), dtype=float32, numpy=0.865458>

## 所有样本的累加损失

In [ ]:
bce = tf.keras.losses.BinaryCrossentropy(from_logits=True, reduction=tf.keras.losses.Reduction.SUM)
bce(labels, logits)

<tf.Tensor: shape=(), dtype=float32, numpy=1.730916>

In [ ]:
bce = tf.keras.losses.BinaryCrossentropy(reduction=tf.keras.losses.Reduction.SUM)
bce(labels, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=1.7309144>

In [ ]:
loss = tf.keras.losses.binary_crossentropy(labels, logits, from_logits=True)
tf.math.reduce_sum(loss)

<tf.Tensor: shape=(), dtype=float32, numpy=1.730916>

In [ ]:
loss = tf.keras.losses.binary_crossentropy(labels, y_pred)
tf.math.reduce_sum(loss)

<tf.Tensor: shape=(), dtype=float32, numpy=6.159179>

In [ ]:
tf.keras.backend.sum(tf.keras.backend.binary_crossentropy(labels, logits, from_logits=True))/logits.shape[1]

<tf.Tensor: shape=(), dtype=float32, numpy=6.163595>

In [ ]:
logits.shape.ndims

2

In [ ]:
tf.keras.backend.ndim(logits)

2